# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-23 12:22
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Title')),
                ('description', models.TextField(verbose_name='Description')),
                ('starter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Event Author')),
            ],
        ),
        migrations.CreateModel(
            name='EventDate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventDate', models.DateField(verbose_name='Event Date')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.Event', verbose_name='Event')),
            ],
        ),
        migrations.CreateModel(
            name='EventTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eventTimeStart', models.TimeField(verbose_name='Event Start Time')),
                ('eventTimeFinish', models.TimeField(verbose_name='Event Finish Time')),
                ('eventDate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.EventDate', verbose_name='Event Date')),
            ],
        ),
        migrations.CreateModel(
            name='Participants',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Full Name')),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('eventTime', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.EventTime', verbose_name='Event Time')),
            ],
        ),
    ]
