# -*- coding: utf-8 -*-
# Generated by Django 1.10.4 on 2017-01-24 23:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('appointment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventdate',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='appointment.Event'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='email',
            field=models.EmailField(max_length=100, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='participants',
            name='eventTime',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='appointment.EventTime'),
        ),
    ]
